import type { TeamSearchResult } from '../../shared/types';

export const FALLBACK_TEAMS: TeamSearchResult[] = [
  {
    id: 109,
    name: 'Arizona Diamondbacks',
    abbreviation: 'ARI',
    locationName: 'Arizona',
    venueName: 'Chase Field',
  },
  {
    id: 144,
    name: 'Atlanta Braves',
    abbreviation: 'ATL',
    locationName: 'Atlanta',
    venueName: 'Truist Park',
  },
  {
    id: 110,
    name: 'Baltimore Orioles',
    abbreviation: 'BAL',
    locationName: 'Baltimore',
    venueName: 'Oriole Park at Camden Yards',
  },
  {
    id: 111,
    name: 'Boston Red Sox',
    abbreviation: 'BOS',
    locationName: 'Boston',
    venueName: 'Fenway Park',
  },
  {
    id: 112,
    name: 'Chicago Cubs',
    abbreviation: 'CHC',
    locationName: 'Chicago',
    venueName: 'Wrigley Field',
  },
  {
    id: 145,
    name: 'Chicago White Sox',
    abbreviation: 'CWS',
    locationName: 'Chicago',
    venueName: 'Guaranteed Rate Field',
  },
  {
    id: 113,
    name: 'Cincinnati Reds',
    abbreviation: 'CIN',
    locationName: 'Cincinnati',
    venueName: 'Great American Ball Park',
  },
  {
    id: 114,
    name: 'Cleveland Guardians',
    abbreviation: 'CLE',
    locationName: 'Cleveland',
    venueName: 'Progressive Field',
  },
  {
    id: 115,
    name: 'Colorado Rockies',
    abbreviation: 'COL',
    locationName: 'Colorado',
    venueName: 'Coors Field',
  },
  {
    id: 116,
    name: 'Detroit Tigers',
    abbreviation: 'DET',
    locationName: 'Detroit',
    venueName: 'Comerica Park',
  },
  {
    id: 117,
    name: 'Houston Astros',
    abbreviation: 'HOU',
    locationName: 'Houston',
    venueName: 'Minute Maid Park',
  },
  {
    id: 118,
    name: 'Kansas City Royals',
    abbreviation: 'KC',
    locationName: 'Kansas City',
    venueName: 'Kauffman Stadium',
  },
  {
    id: 108,
    name: 'Los Angeles Angels',
    abbreviation: 'LAA',
    locationName: 'Los Angeles',
    venueName: 'Angel Stadium',
  },
  {
    id: 119,
    name: 'Los Angeles Dodgers',
    abbreviation: 'LAD',
    locationName: 'Los Angeles',
    venueName: 'Dodger Stadium',
  },
  {
    id: 146,
    name: 'Miami Marlins',
    abbreviation: 'MIA',
    locationName: 'Miami',
    venueName: 'loanDepot park',
  },
  {
    id: 158,
    name: 'Milwaukee Brewers',
    abbreviation: 'MIL',
    locationName: 'Milwaukee',
    venueName: 'American Family Field',
  },
  {
    id: 142,
    name: 'Minnesota Twins',
    abbreviation: 'MIN',
    locationName: 'Minnesota',
    venueName: 'Target Field',
  },
  {
    id: 121,
    name: 'New York Mets',
    abbreviation: 'NYM',
    locationName: 'New York',
    venueName: 'Citi Field',
  },
  {
    id: 147,
    name: 'New York Yankees',
    abbreviation: 'NYY',
    locationName: 'New York',
    venueName: 'Yankee Stadium',
  },
  {
    id: 133,
    name: 'Oakland Athletics',
    abbreviation: 'OAK',
    locationName: 'Oakland',
    venueName: 'Oakland Coliseum',
  },
  {
    id: 143,
    name: 'Philadelphia Phillies',
    abbreviation: 'PHI',
    locationName: 'Philadelphia',
    venueName: 'Citizens Bank Park',
  },
  {
    id: 134,
    name: 'Pittsburgh Pirates',
    abbreviation: 'PIT',
    locationName: 'Pittsburgh',
    venueName: 'PNC Park',
  },
  {
    id: 135,
    name: 'San Diego Padres',
    abbreviation: 'SD',
    locationName: 'San Diego',
    venueName: 'PETCO Park',
  },
  {
    id: 137,
    name: 'San Francisco Giants',
    abbreviation: 'SF',
    locationName: 'San Francisco',
    venueName: 'Oracle Park',
  },
  {
    id: 136,
    name: 'Seattle Mariners',
    abbreviation: 'SEA',
    locationName: 'Seattle',
    venueName: 'T-Mobile Park',
  },
  {
    id: 138,
    name: 'St. Louis Cardinals',
    abbreviation: 'STL',
    locationName: 'St. Louis',
    venueName: 'Busch Stadium',
  },
  {
    id: 139,
    name: 'Tampa Bay Rays',
    abbreviation: 'TB',
    locationName: 'Tampa Bay',
    venueName: 'Tropicana Field',
  },
  {
    id: 140,
    name: 'Texas Rangers',
    abbreviation: 'TEX',
    locationName: 'Texas',
    venueName: 'Globe Life Field',
  },
  {
    id: 141,
    name: 'Toronto Blue Jays',
    abbreviation: 'TOR',
    locationName: 'Toronto',
    venueName: 'Rogers Centre',
  },
  {
    id: 120,
    name: 'Washington Nationals',
    abbreviation: 'WSH',
    locationName: 'Washington',
    venueName: 'Nationals Park',
  },
];
